server:
  port: 8086
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer-01:8083/eureka/,http://peer-02:8084/eureka/
  instance:
      instance-id: ${spring.application.name}:${random.int}
      # 显示ip
      prefer-ip-address: true