server:
  port: 8083
eureka:
  instance:
    hostname: peer-01
  client:
    # 作为注册中心不向注册中心注册自己
    # register-with-eureka: false
    # 注册中心不需要检索服务
    # fetch-registry: false
    serviceUrl:
      defaultZone: http://peer-02:8084/eureka/
spring:
  application:
    name: eureka-server-01