server:
  port: 8085
spring:
  application:
    name: hello-servce
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer-01:8083/eureka/,http://peer-02:8084/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    # 显示ip
    prefer-ip-address: true